### ISSUE TITLE
Online demo takes 30 seconds to add an item to a list

### ISSUE THREAD

**Issue by wjens** [microsoft/TailwindTraders#17]
I was just trying to learn more about this app but it's painful to use.

I was browsing the list of items and picked the first one from here to Add to List.
http://tailwindtraders.com/list/sink

After 30 seconds this page loads
http://tailwindtraders.com/product/detail/9

I'm not logged in and it happens with other items (tried a few).

**Comment by ivilches** [comment]
Hello wjens. 
Was your problem in local too? Anyway, during this time changes have been made that may have fixed the problem.
http://www.tailwindtraders.com/list/sink
http://www.tailwindtraders.com/product/detail/9

**Comment by olgamarti** [comment]
Please, if you are still having this problem, reopen the issue. We will be very happy to help!
