### ISSUE TITLE
Search by photo - dividebyzero exception

### ISSUE THREAD

**Issue by OvrCafn8d** [microsoft/TailwindTraders#22]
trying to set up for a demo of the Tailwind website using product search by image - i am getting: 
Exception thrown: 'System.DivideByZeroException' in Microsoft.ML.OnnxRuntime.dll

I get this using any of the test images in the Documents/TestImages folder

**Comment by dsrodenas** [comment]
Could you please provide more information about the steps you have followed to reproduce the issue?  I have tested with the official deployment (https://www.tailwindtraders.com/) and it works fine. And calling directly through TailwindTraders Backend on an AKS deployment with Postman seems to work fine too:

![image](https://user-images.githubusercontent.com/25981928/75439112-882f8b00-5959-11ea-8830-155738799780.png)

Please provide more information about your issue if possible.

Thanks.

**Comment by OvrCafn8d** [comment]
i had multiple deployments with this issue but i think there was something i must have fat-fingered on the deployment template becuase in my latest deployment today it is working correctly.
