### ISSUE TITLE
Integrating Azure Pipelines, GitHub, and Azure Boards - Build fails because of userEmail parameter

### ISSUE THREAD

**Issue by MarkWme** [microsoft/TailwindTraders#3]
Following through the Azure Pipelines, GitHub and Azure Boards script, the build pipeline created by the Azure DevOps Demo Generator fails at the "Azure Deployment:Create Or Update Resource Group action on $(resourcegroup)" step as follows

```
##[error]Deployment template validation failed: 'The template parameters 'userEmail' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are 'sku, skuCode, registrySku, workerSize, dockerRegistryUrl, dockerimage, apiBaseUrl'. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'.
##[error]Task failed while creating or updating the template deployment.
```

The `override template parameters` section of the step contains a value `-userEmail $(useremail)` removing this value allows the build to proceed.

**Comment by CanarysAutomations** [comment]
Hi Mark, thank you for pointing out the issue. We have fixed the issue in the Tailwind Traders template of Azure DevOps Demo Generator.
