### ISSUE TITLE
Integrating Azure Pipelines, GitHub, and Azure Boards - Build fails because of missing Dockerfile

### ISSUE THREAD

**Issue by MarkWme** [microsoft/TailwindTraders#4]
Following through the Azure Pipelines, GitHub and Azure Boards script, the build pipeline created by the Azure DevOps Demo Generator fails at the Build an Image step.  The error is as follows:

`##[error]Unhandled: No Dockerfile matching  /home/vsts/work/1/s/Source/Dockerfile  was found.`

The `Dockerfile` section of the step contains a value of `Source/Dockerfile` which appears to be incorrect. Updating this value to `Source/Tailwind.Traders.Web/Dockerfile` allows the build to progress.

**Comment by AshWilliams** [comment]
You need to select the Dockerfile using the search dialog at the docker build task in your pipeline.

**Comment by CanarysAutomations** [comment]
Hi Mark, thank you for pointing out the issue. We have corrected it in the template of Azure DevOps Demo Generator. You should now be able to have a successful build.
